"""Add description and is_active to campaigns

Revision ID: 3531fa35359f
Revises: 6c369edd2a4c
Create Date: 2020-04-16 16:16:41.113339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3531fa35359f'
down_revision = '6c369edd2a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('description', sa.Text(), server_default='', nullable=False))
    op.add_column('campaign', sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'is_active')
    op.drop_column('campaign', 'description')
    # ### end Alembic commands ###
